/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsIndexRouteImport } from './routes/songs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SongsNewRouteImport } from './routes/songs/new'
import { Route as SongsSlugRouteImport } from './routes/songs/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminCoversRouteImport } from './routes/admin/covers'
import { Route as AdminSongsIndexRouteImport } from './routes/admin/songs.index'
import { Route as AdminSongsIdRouteImport } from './routes/admin/songs.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SongsNewRoute = SongsNewRouteImport.update({
  id: '/songs/new',
  path: '/songs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSlugRoute = SongsSlugRouteImport.update({
  id: '/songs/$slug',
  path: '/songs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoversRoute = AdminCoversRouteImport.update({
  id: '/covers',
  path: '/covers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSongsIndexRoute = AdminSongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSongsIdRoute = AdminSongsIdRouteImport.update({
  id: '/songs/$id',
  path: '/songs/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/covers': typeof AdminCoversRoute
  '/admin/users': typeof AdminUsersRoute
  '/songs/$slug': typeof SongsSlugRoute
  '/songs/new': typeof SongsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/songs': typeof SongsIndexRoute
  '/admin/songs/$id': typeof AdminSongsIdRoute
  '/admin/songs': typeof AdminSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/changelog': typeof ChangelogRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/covers': typeof AdminCoversRoute
  '/admin/users': typeof AdminUsersRoute
  '/songs/$slug': typeof SongsSlugRoute
  '/songs/new': typeof SongsNewRoute
  '/admin': typeof AdminIndexRoute
  '/songs': typeof SongsIndexRoute
  '/admin/songs/$id': typeof AdminSongsIdRoute
  '/admin/songs': typeof AdminSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/covers': typeof AdminCoversRoute
  '/admin/users': typeof AdminUsersRoute
  '/songs/$slug': typeof SongsSlugRoute
  '/songs/new': typeof SongsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/admin/songs/$id': typeof AdminSongsIdRoute
  '/admin/songs/': typeof AdminSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/changelog'
    | '/login'
    | '/register'
    | '/admin/covers'
    | '/admin/users'
    | '/songs/$slug'
    | '/songs/new'
    | '/admin/'
    | '/songs'
    | '/admin/songs/$id'
    | '/admin/songs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/changelog'
    | '/login'
    | '/register'
    | '/admin/covers'
    | '/admin/users'
    | '/songs/$slug'
    | '/songs/new'
    | '/admin'
    | '/songs'
    | '/admin/songs/$id'
    | '/admin/songs'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/changelog'
    | '/login'
    | '/register'
    | '/admin/covers'
    | '/admin/users'
    | '/songs/$slug'
    | '/songs/new'
    | '/admin/'
    | '/songs/'
    | '/admin/songs/$id'
    | '/admin/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SongsSlugRoute: typeof SongsSlugRoute
  SongsNewRoute: typeof SongsNewRoute
  SongsIndexRoute: typeof SongsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/songs/new': {
      id: '/songs/new'
      path: '/songs/new'
      fullPath: '/songs/new'
      preLoaderRoute: typeof SongsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$slug': {
      id: '/songs/$slug'
      path: '/songs/$slug'
      fullPath: '/songs/$slug'
      preLoaderRoute: typeof SongsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/covers': {
      id: '/admin/covers'
      path: '/covers'
      fullPath: '/admin/covers'
      preLoaderRoute: typeof AdminCoversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/songs/': {
      id: '/admin/songs/'
      path: '/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof AdminSongsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/songs/$id': {
      id: '/admin/songs/$id'
      path: '/songs/$id'
      fullPath: '/admin/songs/$id'
      preLoaderRoute: typeof AdminSongsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCoversRoute: typeof AdminCoversRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSongsIdRoute: typeof AdminSongsIdRoute
  AdminSongsIndexRoute: typeof AdminSongsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoversRoute: AdminCoversRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSongsIdRoute: AdminSongsIdRoute,
  AdminSongsIndexRoute: AdminSongsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SongsSlugRoute: SongsSlugRoute,
  SongsNewRoute: SongsNewRoute,
  SongsIndexRoute: SongsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
