/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsIndexRouteImport } from './routes/songs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SongsSlugRouteImport } from './routes/songs/$slug'
import { Route as AdminCoversRouteImport } from './routes/admin/covers'
import { Route as AdminSongsIndexRouteImport } from './routes/admin/songs.index'
import { Route as AdminSongsIdRouteImport } from './routes/admin/songs.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSlugRoute = SongsSlugRouteImport.update({
  id: '/songs/$slug',
  path: '/songs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoversRoute = AdminCoversRouteImport.update({
  id: '/admin/covers',
  path: '/admin/covers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSongsIndexRoute = AdminSongsIndexRouteImport.update({
  id: '/admin/songs/',
  path: '/admin/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSongsIdRoute = AdminSongsIdRouteImport.update({
  id: '/admin/songs/$id',
  path: '/admin/songs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/covers': typeof AdminCoversRoute
  '/songs/$slug': typeof SongsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/songs': typeof SongsIndexRoute
  '/admin/songs/$id': typeof AdminSongsIdRoute
  '/admin/songs': typeof AdminSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/covers': typeof AdminCoversRoute
  '/songs/$slug': typeof SongsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/songs': typeof SongsIndexRoute
  '/admin/songs/$id': typeof AdminSongsIdRoute
  '/admin/songs': typeof AdminSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/covers': typeof AdminCoversRoute
  '/songs/$slug': typeof SongsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/admin/songs/$id': typeof AdminSongsIdRoute
  '/admin/songs/': typeof AdminSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/covers'
    | '/songs/$slug'
    | '/admin'
    | '/songs'
    | '/admin/songs/$id'
    | '/admin/songs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/covers'
    | '/songs/$slug'
    | '/admin'
    | '/songs'
    | '/admin/songs/$id'
    | '/admin/songs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/covers'
    | '/songs/$slug'
    | '/admin/'
    | '/songs/'
    | '/admin/songs/$id'
    | '/admin/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminCoversRoute: typeof AdminCoversRoute
  SongsSlugRoute: typeof SongsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SongsIndexRoute: typeof SongsIndexRoute
  AdminSongsIdRoute: typeof AdminSongsIdRoute
  AdminSongsIndexRoute: typeof AdminSongsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$slug': {
      id: '/songs/$slug'
      path: '/songs/$slug'
      fullPath: '/songs/$slug'
      preLoaderRoute: typeof SongsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/covers': {
      id: '/admin/covers'
      path: '/admin/covers'
      fullPath: '/admin/covers'
      preLoaderRoute: typeof AdminCoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/songs/': {
      id: '/admin/songs/'
      path: '/admin/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof AdminSongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/songs/$id': {
      id: '/admin/songs/$id'
      path: '/admin/songs/$id'
      fullPath: '/admin/songs/$id'
      preLoaderRoute: typeof AdminSongsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminCoversRoute: AdminCoversRoute,
  SongsSlugRoute: SongsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  SongsIndexRoute: SongsIndexRoute,
  AdminSongsIdRoute: AdminSongsIdRoute,
  AdminSongsIndexRoute: AdminSongsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
